version: "3"
services:
  frontend:
    image: frontend
    build:
      context: client
      dockerfile: dockerfile
    environment:
      - PORT=3000

    ports:
      - "3000:3000"

  backend:
    image: backend
    build: server
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
